"use client";
import React from "react";
import Header from "../components/Header";
import Footer from "../components/Footer";

export default function Page() {
  return (
    <>
      <Header />
      <div className="my-5 py-5">
        <div className="my-5"></div>
      </div>
      <div className="max-w-4xl mx-auto px-4 py-8">
        <h2 className="text-2xl font-bold mb-4">Terms and Conditions</h2>
        <p className="mb-4">Last Updated: 29 Nov 2024</p>

        <p className="mb-4">
          Welcome to Clear Terms! By accessing or using our website and
          services, you agree to comply with and be bound by these Terms and
          Conditions. Please read them carefully.
        </p>

        <h3 className="text-xl font-semibold mt-6 mb-2">1. Introduction</h3>
        <p className="mb-4">
          Clear Terms is a platform that uses artificial intelligence to
          simplify and summarize legal documents. Our goal is to make legal
          information more accessible and understandable. However, our AI-based
          service is not a substitute for professional legal advice.
        </p>

        <h3 className="text-xl font-semibold mt-6 mb-2">
          2. Acceptance of Terms
        </h3>
        <p className="mb-4">
          By using our services, you agree to these Terms and Conditions, along
          with any updates that may be made from time to time. If you do not
          agree to any part of these Terms, you must not use our services.
        </p>

        <h3 className="text-xl font-semibold mt-6 mb-2">3. AI Disclaimer</h3>
        <p className="mb-4">
          Clear Terms uses AI technology to analyze and simplify legal
          documents. While we strive for accuracy, AI-generated content may
          contain errors, omissions, or misinterpretations. The information
          provided by Clear Terms is for informational purposes only and should
          not be relied upon as legal advice.
        </p>
        <p className="mb-4">
          Users are encouraged to verify the simplified information with a legal
          professional and should not rely solely on the content generated by
          our platform.
        </p>

        <h3 className="text-xl font-semibold mt-6 mb-2">
          4. No Attorney-Client Relationship
        </h3>
        <p className="mb-4">
          Using Clear Terms does not create an attorney-client relationship
          between you and Clear Terms or any affiliated parties. If you need
          legal advice, please consult a qualified attorney.
        </p>

        <h3 className="text-xl font-semibold mt-6 mb-2">
          5. User Responsibilities
        </h3>
        <ul className="list-disc list-inside mb-4">
          <li>
            You agree to use Clear Terms responsibly and for lawful purposes
            only.
          </li>
          <li>
            You must not use the service to interpret complex legal information
            without consulting a qualified professional.
          </li>
        </ul>

        <h3 className="text-xl font-semibold mt-6 mb-2">
          6. Limitation of Liability
        </h3>
        <p className="mb-4">
          Clear Terms, its affiliates, and its staff shall not be liable for any
          damages arising from your use of our AI-generated content. This
          includes, but is not limited to, inaccuracies, errors, or omissions in
          the information provided by the platform.
        </p>
        <p className="mb-4">
          We are not responsible for any actions or decisions made based on the
          content generated by our AI, and we strongly advise all users to
          independently verify information with a legal professional.
        </p>

        <h3 className="text-xl font-semibold mt-6 mb-2">
          7. Intellectual Property
        </h3>
        <p className="mb-4">
          All content, software, and services provided on Clear Terms are the
          intellectual property of Clear Terms or its licensors. You may not
          reproduce, distribute, or create derivative works from our content
          without explicit permission.
        </p>

        <h3 className="text-xl font-semibold mt-6 mb-2">
          8. Third-Party Services
        </h3>
        <p className="mb-4">
          Our service may integrate or reference third-party tools or websites.
          We are not responsible for the content, services, or practices of
          these third parties. Your use of third-party services is at your own
          risk and subject to the terms and conditions of those third parties.
        </p>

        <h3 className="text-xl font-semibold mt-6 mb-2">9. Changes to Terms</h3>
        <p className="mb-4">
          Clear Terms reserves the right to modify these Terms and Conditions at
          any time. We will notify users of significant changes by posting an
          updated version on our website. Your continued use of the platform
          constitutes acceptance of the revised Terms.
        </p>

        <h3 className="text-xl font-semibold mt-6 mb-2">
          10. Termination of Service
        </h3>
        <p className="mb-4">
          Clear Terms reserves the right to terminate or suspend access to our
          services for any user who violates these Terms and Conditions, at our
          discretion and without prior notice.
        </p>

        <h3 className="text-xl font-semibold mt-6 mb-2">11. Governing Law</h3>
        <p className="mb-4">
          These Terms and Conditions are governed by the laws of
          [Country/Region]. Any legal disputes arising from the use of Clear
          Terms will be subject to the exclusive jurisdiction of the courts in
          [Location].
        </p>

        <h3 className="text-xl font-semibold mt-6 mb-2">12. Contact Us</h3>
        <p className="mb-4">
          If you have any questions regarding these Terms and Conditions, please
          contact us at support@clearterms.ai.
        </p>
      </div>
      <Footer />
    </>
  );
}
